### ISSUE TITLE
Update the GitHub repo description to indicate support for IPython 4.x/Jupyter

### ISSUE THREAD

**Issue by AustinRochford** [monetate/s3nb#28]
@krismolendyke

**Comment by krismolendyke** [comment]
You have `write` perms :wink:

**Comment by krismolendyke** [comment]
Oh, the actual description in the GitHub UI?  I guess that's `admin` only?

**Comment by krismolendyke** [comment]
:ballot_box_with_check:

**Comment by AustinRochford** [comment]
Thanks

**Comment by max-sixty** [comment]
Do you want to indicate it's for Jupyter? Or you think people still refer to it as IPython?
