### ISSUE TITLE
Save to S3 in a background thread

### ISSUE THREAD

**Issue by AustinRochford** [monetate/s3nb#31]
Sometimes (depending on many factors) saving to S3 can produce a noticeable delay.

Saving in a background thread would prevent this, I think?  @raphaellig?

**Comment by graphaelli** [comment]
This means returning from https://github.com/monetate/s3nb/blob/37216893e04e91463910f8ee8604523dc92651b2/s3nb/ipy3.py#L312 without actually ensuring s3 is written to?  How would signal to the user that the save failed?

**Comment by AustinRochford** [comment]
Hmm, that's a good point. :(

On Thu, Apr 7, 2016 at 3:41 PM, Gil Raphaelli notifications@github.com
wrote:

> This means returning from
> https://github.com/monetate/s3nb/blob/37216893e04e91463910f8ee8604523dc92651b2/s3nb/ipy3.py#L312
> without actually ensuring s3 is written to? How would signal to the user
> that the save failed?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/monetate/s3nb/issues/31#issuecomment-207061627

## 

## 

_Austin Rochford_
Principal Data Scientist @ Monetate
o: (877) 666-3828 x382 | m:
arochford@monetate.com

Watch our Video
http://content.monetate.com/h/i/11572086-welcome-to-monetate | Marketing
Blog http://monetate.com/blog/ | Free Resources
http://monetate.com/resources/ | Follow Monetate on Twitter
http://twitter.com/monetate
http://www.monetatesummit.com
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
